# -*- encoding: utf-8 -*-
#Triangle, pentagonal, and hexagonal numbers are generated by the following formulae:
#Triangle      Tn=n(n+1)/2     1, 3, 6, 10, 15, ...
#Pentagonal    Pn=n(3n−1)/2    1, 5, 12, 22, 35, ...
#Hexagonal     Hn=n(2n−1)      1, 6, 15, 28, 45, ...

#It can be verified that T285 = P165 = H143 = 40755.

#Find the next triangle number that is also pentagonal and hexagonal.

llimit = 20000
ulimit = 60000

tnumbers = []
for n in range(llimit, ulimit):
	tnumbers.append((n*(n+1))/2)

pnumbers = set()
for n in range(llimit, ulimit):
	pnumbers.add((n*(3*n-1))/2)

hnumbers = set()
for n in range(llimit, ulimit):
	hnumbers.add(n*(2*n-1))

for number in tnumbers:
	if number in pnumbers:
		if number in hnumbers: print number

